name: Android Unit Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Access API_KEYS
      env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      run: 
        echo google_api_key=\"GOOGLE_API_KEY\" >> ./local.properties ; echo weather_api_key=\"WEATHER_API_KEY\" >> ./local.properties
        
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew createDebugCoverageReport

    - name: Upload Lint And Code Coverage Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Lint Results And Coverage
        path: |
            app/build/reports/lint-results-debug.html
            app/build/reports/coverage/test/debug/

            
            

